const states = [
    { initials: 'AC', name: 'Acre' },
    { initials: 'AL', name: 'Alagoas' },
    { initials: 'AP', name: 'Amapá' },
    { initials: 'AM', name: 'Amazonas' },
    { initials: 'BA', name: 'Bahia' },
    { initials: 'CE', name: 'Ceará' },
    { initials: 'DF', name: 'Distrito Federal' },
    { initials: 'ES', name: 'Espírito Santo' },
    { initials: 'GO', name: 'Goiás' },
    { initials: 'MA', name: 'Maranhão' },
    { initials: 'MT', name: 'Mato Grosso' },
    { initials: 'MS', name: 'Mato Grosso do Sul' },
    { initials: 'MG', name: 'Minas Gerais' },
    { initials: 'PA', name: 'Pará' },
    { initials: 'PB', name: 'Paraíba' },
    { initials: 'PR', name: 'Paraná' },
    { initials: 'PE', name: 'Pernambuco' },
    { initials: 'PI', name: 'Piauí' },
    { initials: 'RJ', name: 'Rio de Janeiro' },
    { initials: 'RN', name: 'Rio Grande do Norte' },
    { initials: 'RS', name: 'Rio Grande do Sul' },
    { initials: 'RO', name: 'Rondônia' },
    { initials: 'RR', name: 'Roraima' },
    { initials: 'SC', name: 'Santa Catarina' },
    { initials: 'SP', name: 'São Paulo' },
    { initials: 'SE', name: 'Sergipe' },
    { initials: 'TO', name: 'Tocantins' }
]

export default states